# This script merges multiple TSV files from different
# directories into a single file for each directory.
setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 1")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)

setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 2")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)

setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 3")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)

setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 4")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)

setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 5")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)

setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 6")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)

setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 7")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)

setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 8")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)

setwd("C:/Graham/TCGA_AML_BEAT1_0/Raw Data/part 9")
file_list <- list.files(pattern = "*.tsv")
list_of_files <- lapply(file_list, read.delim, sep='\t', skip=6)
DF<-Reduce(function(x, y) merge(x, y, all=TRUE, by=0), list_of_files)
write.table(DF, file = "merged.txt", sep = "\t",row.names = F,col.names = T)
write.table(file_list, file="filenames.txt", sep="\t",row.names =T, col.names=T)